// AssemblyInfo.cs - Updated for .NET 8 / SDK-style project compatibility
// CHANGES:
//   - In SDK-style .csproj (net8.0-windows), AssemblyTitle, AssemblyDescription,
//     AssemblyConfiguration, AssemblyCompany, AssemblyProduct, AssemblyCopyright,
//     AssemblyTrademark, AssemblyVersion, and AssemblyFileVersion are auto-generated
//     from project properties. Duplicate declarations here would cause CS0579 errors.
//   - Retained only attributes NOT auto-generated by the SDK: ComVisible and Guid.
//   - AssemblyCulture is also auto-generated; removed to avoid duplication.

using System.Runtime.InteropServices;

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components. If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("e43a2363-b317-43ca-aaa6-e2b3eea26fe4")]
