<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>BankManagementSystem</RootNamespace>
    <AssemblyName>BankManagementSystem</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="log4net" Version="2.0.17" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.59" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="Experimental.System.Messaging" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankDatabaseAccess\BankDatabaseAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="CutomerDashboardForms\Transfer.resx">
      <DependentUpon>Transfer.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="CutomerDashboardForms\Home.resx">
      <DependentUpon>Home.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="CutomerDashboardForms\Withdraw.resx">
      <DependentUpon>Withdraw.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="CustomerDashBoard.resx">
      <DependentUpon>CustomerDashBoard.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="EmployeeDashBoard.resx">
      <DependentUpon>EmployeeDashBoard.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="EmployeeDashboardForms\CustomerInfo.resx">
      <DependentUpon>CustomerInfo.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="EmployeeDashboardForms\Deposit.resx">
      <DependentUpon>Deposit.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="EmployeeDashboardForms\EditInfo.resx">
      <DependentUpon>EditInfo.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="EmployeeDashboardForms\Home.resx">
      <DependentUpon>Home.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="LoginUI.resx">
      <DependentUpon>LoginUI.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <SubType>Designer</SubType>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="RegistrationUI.resx">
      <DependentUpon>RegistrationUI.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="WelcomeUI.resx">
      <DependentUpon>WelcomeUI.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\Logo.png" />
    <None Include="Resources\dpHolder.png" />
    <None Include="Resources\cardHolder.png" />
    <None Include="Resources\getStarted_.png" />
    <None Include="Resources\gitIcon.png" />
  </ItemGroup>

</Project>
